### ISSUE TITLE
감사합니다.

### ISSUE THREAD

**Issue by MyType9591** [CausalInferenceLab/Causal-Inference-with-Python#27]
이렇게 좋은 자료를 예술적으로 번역해주신 가짜연구소 스터디원 분들께 찬사를 보냅니다!

**Comment by jsshin2022** [comment]
안녕하세요! 저희 인과추론 자료에 대해 관심가져주셔서 매우 감사합니다 :-) 
앞으로 많은 자료가 업로드될 예정이니, 많은 관심 부탁드립니다
