### ISSUE TITLE
오타 발견

### ISSUE THREAD

**Issue by chulhongsung** [CausalInferenceLab/Causal-Inference-with-Python#63]
10장 Matching에서 The Curse of Dimensionality 부분에 3^{10}으로 들어가야할 부분이 3^10으로 들어가서 오타가 발생한것 같습니다.

**Comment by YejoongKwon** [comment]
안녕하세요, 인과추론 13장. 이중차분(DID) 에서 저도 오타인지 확인하고 싶어 여쭙습니다

위 식은 개입 전 처치된 그룹에 추세 구성 요소를 추가된 것을 보여주고 있어요. 대조군 $E[Y_0(1)|D=0] - E[Y_0(0)|D=0

이라는 본문 바로 위에 식에, 우측 첫번째 항의 Y_{0}(0)|D=1 이 Y_{1}(0)|D=1 이 되어야 평행 추세 가정을 설명할 수 있을 것 같습니다
