### ISSUE TITLE
13장 DID 오타 발견

### ISSUE THREAD

**Issue by YejoongKwon** [CausalInferenceLab/Causal-Inference-with-Python#66]
안녕하세요, 인과추론 13장. 이중차분(DID) 에서 저도 오타인지 확인하고 싶어 여쭙습니다

위 식은 개입 전 처치된 그룹에 추세 구성 요소를 추가된 것을 보여주고 있어요. 대조군 $E[Y_0(1)|D=0] - E[Y_0(0)|D=0

이라는 본문 바로 위에 식에, 우측 첫번째 항의 E[ Y_{0}(0)|D=1] 이라고 되어있는데 이게 E[Y_{1}(0)|D=1] 이 되어야 평행 추세 가정을 설명할 수 있을 것 같습니다

별도로, 좋은 자료를 번역해 주셔서 감사하다는 말씀 전합니다

**Comment by jsshin2022** [comment]
확인해보고 말씀드리겠습니다!

**Comment by chulhongsung** [comment]
안녕하세요, E[Y_{0}(0)|D=1]이 맞다고 생각됩니다. 우리가 관측하지 못하는 반사실(counterfactual)는 E[Y_{0}(0)|D=1] 처치를 한 도시의 처치를 하지 않았을 때, 시간이 경과된 결과이기 때문입니다. 따라서 E[Y_{0}(1)|D=1] = E[Y_{0}(0)|D=1] + (E[Y_{0}(1)|D=0] - E[Y_{0}(0)|D=0])로 추정을 한다고 이해했습니다. 말씀하신 평행 추세 가정은 뒤의 (E[Y_{0}(1)|D=0] - E[Y_{0}(0)|D=0])이 원래는 (E[Y_{0}(1)|D=1] - E[Y_{0}(0)|D=1]) 이어야하지만 두 값이 동일하므로 대체했다고 보았습니다. 혹시 잘못된 부분이 있으면 의견 부탁드립니다.
