### ISSUE TITLE
10 Matching 오타 발견

### ISSUE THREAD

**Issue by be-favorite** [CausalInferenceLab/Causal-Inference-with-Python#68]
오타를 발견했습니다:

![image](https://github.com/CausalInferenceLab/Causal-Inference-with-Python/assets/70742085/8675262f-6fac-4a31-8db8-4d1bf1693584)

-> $Y_{jm}(i)$는 $Y_(i)$와 가장 유사한 다른 처치 그룹의 표본을 의미합니다.

로 수정 필요합니다.

**Comment by jsshin2022** [comment]
안녕하세요, 가짜연구소 인과추론팀 번역자료에 관심 가져주셔서 감사합니다 :-) 
해당 부분 수정해놓았으며, 곧 배포하도록 하겠습니다!
